inherit_from: .rubocop_todo.yml

require: 
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
    - "lib/*"
    - "lib/**/*"
  DisplayCopNames: true

AsciiComments:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
    Exclude:
      - 'spec/**/*'